# Generated by Django 2.1.7 on 2019-03-21 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190320_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='avatar',
            new_name='article_image',
        ),
    ]
